services:
  php:
    image: php:8.2-apache
    container_name: php_82
    ports:
      - 8000:80
    volumes:
      - ./php:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: mysql:8.0
    container_name: mysql_8
    environment:
      MYSQL_ROOT_PASSWORD: LebenForm404
      MYSQL_DATABASE: taskmanager
      MYSQL_USER: debianDev
      MYSQL_PASSWORD: LebenForm404
    ports:
      - "3307:3306"